<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '',
    'Are you sure you want to delete this item?' => '',
    'Avatar Name' => '',
    'Avatar Path' => '',
    'Category Track' => '',
    'Create' => '',
    'Create News' => '',
    'Create News Category' => '',
    'Created At' => '',
    'Created User' => '',
    'Delete' => '',
    'Meta Description' => '',
    'Meta Keywords' => '',
    'Meta Title' => '',
    'News' => '',
    'News Categories' => '',
    'News Category ID' => '',
    'News Content' => '',
    'News Hot' => '',
    'News ID' => '',
    'News Short Desc' => 'Mô tả ngắn',
    'News Source' => '',
    'News Title' => '',
    'Poster' => '',
    'Publicdate' => '',
    'Reset' => '',
    'Search' => '',
    'Status' => '',
    'Translatable String' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Viewed' => '',
];
